# Trade Indices Numbers - Methodology {#methodology}

The trade index numbers calculated by the Food and Agriculture Organization (FAO) are statistical measures used to track and analyze changes in international agricultural trade. These index numbers provide a comprehensive view of the global agricultural trade trends by comparing trade volumes and values over time.\
The formula used for calculating these index numbers is based on the Laspeyres formula, a widely used method for constructing price or quantity indices. The Laspeyres formula compares the current period's trade values or quantities with those of a chosen reference period, calculating the ratio between them. The reference period, also named base period, is estimated through a three year mean around the selected base year. The calculated ratio is multiplied by 100 to express the result as a percentage and it represents the relative change in trade over time.\
By applying the Laspeyres formula to agricultural trade data, FAO generates trade index numbers that capture the changes in trade volumes or values for specific commodities or commodity groups, facilitating meaningful comparisons and analysis of global agricultural trade patterns.


## Base periode quantities

The base quantities and prices for the calculation of the indices follows the following formulas : 

### Base Import Quantity

Base Import Quantity $(BIQ)$ is calculated as the Import Quantity at time $t$ $(IQ_t)$ divided by the three year average of the Import Quantity around base year $(IQ_0)$.

```{=tex}
\begin{equation} 
 BIQ_{t} = \frac{{IQ}_t}{{IQ}_0}
 
 (\#eq:eq461)
\end{equation}
```

### Base Export Quantity 

Base Export Quantity $(BEQ)$ is calculated as the Export Quantity at time $t$ $(EQ_t)$ divided by the three year average of the Export Quantity around base year $(EQ_0)$.


```{=tex}
\begin{equation} 
 BEQ_{t} = \frac{{EQ}_t}{{EQ}_0}

(\#eq:eq491)
\end{equation}
```
<br>

### Import Value Base Period Quantity

Import Value Base Period Quantity $(IVBPQ)$ is calculated as the Import Value $(IV_t)$ divided by Base Import Quantity $(BIQ_t)$ defined in eq. \@ref(eq:eq461).

```{=tex}
\begin{equation} 
 IVBPQ_{t} = \frac{{IV}_t}{{BIQ}_t}

(\#eq:eq64)
\end{equation}
```
<br>

### Export Value Base Period Quantity

Export Value Base Period Quantity $(EVBPQ)$ is calculated as the Import Value $(EV_t)$ divided by Base Export Quantity $(BEQ_t)$ defined in eq. \@ref(eq:eq491)..

```{=tex}
\begin{equation} 
 EVBPQ_{t} = \frac{{EV}_t}{{BEQ}_t}

(\#eq:eq94)
\end{equation}
```
<br>

### Import Value Base Period Price

Import Value Base Period Price $(IVBPP)$ is calculated as the three years average base Import Value $(IV_0)$ multiplied by Base Import Quantity $(BIQ_t)$ defined in eq. \@ref(eq:eq461).

```{=tex}
\begin{equation} 
 IVBPP_{t} = IV_0 * BIQ_t

(\#eq:eq65)
\end{equation}
```
<br>

### Export Value Base Period Price

Import Value Base Period Price $(EVBPP)$ is calculated as the three years average base Import Value $(EV_0)$ multiplied by Base Import Quantity $(BEQ_t)$ defined in eq. \@ref(eq:eq491).

```{=tex}
\begin{equation} 
 EVBPP_{t} = EV_0 * BEQ_t

(\#eq:eq95)
\end{equation}
```
<br>

## Trade indices

The Trade indices are calculated with the following formulas : 

### Import Value Index 

Import Value Index  is calculated as Import Value $(IV_t)$ divided by three years average of Import Value $(IV_0)$, then multiplied by 100.

```{=tex}
\begin{equation} 
 IVI_{t} = \frac{IV_t}{IV_0} * 100

(\#eq:eq462)
\end{equation}
```
<br>

### Export Value Index 

Export Value Index  is calculated as Import Value $(EV_t)$ divided by three years average of Emport Value $(EV_0)$, then multiplied by 100.

```{=tex}
\begin{equation} 
 EVI_{t} = \frac{EV_t}{EV_0} * 100

(\#eq:eq492)
\end{equation}
```
<br>

### Import Unit/Value Index

Import Unit/Value Index $(IUVI)$  is calculated as Import Value Base Period Quantity $(IVBPQ_t)$, calculated in \@ref(eq:eq64), divided by its three year average around base year $(IVBPQ_0)$.

```{=tex}
\begin{equation} 
 IUVI_{t} = \frac{IVBPQ_t}{IVBPQ_0} * 100

(\#eq:eq464)
\end{equation}
```

<br>

### Export Unit/Value Index

Export Unit/Value Index $(EUVI)$  is calculated as Export Value Base Period Quantity $(EVBPQ_t)$, calculated in \@ref(eq:eq94), divided by its three year average around base year $(EVBPQ_0)$.

```{=tex}
\begin{equation} 
 EUVI_{t} = \frac{EVBPQ_t}{EVBPQ_0} * 100

(\#eq:eq494)
\end{equation}
```

<br>

### Import Quantity Index

Import Quantity Index $(IQI)$  is calculated as Import Value Base Period Price $(IVBPP_t)$, calculated in \@ref(eq:eq65), divided by its three year average around base year $(IVBPP_0)$.

```{=tex}
\begin{equation} 
 IQI_{t} = \frac{IVBPP_t}{IVBPP_0} * 100

(\#eq:eq465)
\end{equation}
```

<br>

### Export Quantity Index

Export Quantity Index $(EQI)$  is calculated as Export Value Base Period Price $(EVBPP_t)$, calculated in \@ref(eq:eq95), divided by its three year average around base year $(EVBPP_0)$.

```{=tex}
\begin{equation} 
 EQI_{t} = \frac{EVBPP_t}{EVBPP_0} * 100

(\#eq:eq495)
\end{equation}
```

<br>

## FOB and CIF

Most countries report export values as Free-On-Board (FOB. i.e. insurance/transport costs are
not included), while import values are mostly reported as Cost-Insurance-Freight (CIF. i.e.
insurance/transport costs are included).\
For the following countries both imports and exports are FOB: Australia, Bermuda, Bulgaria,
Canada, Czechoslovakia, Dominican Republic, Mexico (from 1992 to 1994), Papua New
Guinea, Paraguay, Poland, Solomon Islands, South Africa, USSR, Venezuela, Zambia and
Zimbabwe.\
For the calculation of the index numbers the import values for these countries were
converted into CIF by a standard conversion factor .